version: '3.8'

services:
  arangodb:
    build:
      context: .
      dockerfile: Dockerfile.arangodb
    command: ["--server.storage-engine=rocksdb"]
    container_name: ${ARANGO_CONTAINER_NAME:-hades_arangodb}
    environment:
      # For local development, you can use a simple password
      - ARANGO_ROOT_PASSWORD=devpassword
      # For production, uncomment and set this:
      # - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
      # Additional security settings
      - ARANGO_NO_AUTH=0
      - ARANGO_STORAGE_ENGINE=rocksdb
    ports:
      - "${ARANGO_PORT:-8529}:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps:/var/lib/arangodb3-apps
    networks:
      - hades_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  hades_network:
    name: ${DOCKER_NETWORK_NAME:-hades_network}
    driver: bridge

volumes:
  arango_data:
    name: ${ARANGO_DATA_VOLUME:-hades_arango_data}
  arango_apps:
    name: ${ARANGO_APPS_VOLUME:-hades_arango_apps}
